### ISSUE TITLE
How to use the example yaml file

### ISSUE THREAD

**Issue by ZihanZhang0** [acclimate/acclimate#8]
Hi, I have done the cmake and make of acclimate. 
I used `./acclimate BASED_ON_INT | home/Downloads/acclimate/lib/libmrio/examples/simple/settings.yml` under the build folder, but the terminal showed `Settings '//model' not found`. 
I saw the info `Enabled variants:       VARIANT_BASIC, VARIANT_DEMAND, VARIANT_PRICES
Enabled options:        BASED_ON_INT, BANKERS_ROUNDING` but I don't know how to use them as a beginner. I wonder if it is convenient to you to provide a more precise example? Thank you so much.

**Comment by swillner** [comment]
Hey, I am sorry that we cannot give support on running the model here on GitHab. I just replied to your mail, though ;)

**Comment by zeroxsc** [comment]
hi,do  you know how to use the model now?
